#set page(margin: 24mm)
#set text(size: 10.5pt)
#set par(justify: true)
#set page(numbering: "1")

#align(center)[
  #text(size: 18pt, weight: "bold")[MCTS-in-Enumeration]
  #linebreak()
  #text(size: 11pt)[Logic for SVP Search]
]

= Notations

== Lattice and Enumeration

- $B = (b_1, b_2, dots, b_n)$: the current lattice basis.
- $L(B)$: the lattice generated by $B$.
- $i$: position index.
- $b_i$: the $i$-th basis vector.
- $b_i^*$: the $i$-th Gram-Schmidt orthogonalized (GSOed) vector.
- $n$: lattice dimension.
- $k$: current enumeration depth.
- $ZZ$: set of Integers.
- $z = (z_1, dots, z_n)$: integer coefficient vector.
- $z_k$: the actual integer coefficient selected at depth $k$.
- $v = B z = sum_(i=1)^n z_i b_i$: the complete lattice vector represented by $z$.
- $G H$: Gaussian Heuristic, used as a reference length for the found SV's quality.
- $G S O$: Gram-Schmidt orthogonalization.

== GSO Geometry and Exact Bounds

- Gram-Schmidt decomposition:

$
  b_i
  =
  b_i^*
  +
  sum_(j=1)^(i-1)
  mu_(i,j) b_j^*.
$

- $mu_(i,k)$: Gram-Schmidt projection coefficient.
It describes how much of the original basis vector $b_i$ lies in the orthogonal direction $b_k^*$. It is a geometric property of the current basis, not an action selected by MCTS.

- $g_k$: squared GSO length,
  $
    g_k = norm(b_k^*)^2.
  $
  It measures how expensive a residual displacement is in the $k$-th orthogonal direction.

- $c_k$: conditional Gram-Schmidt center for the next integer coefficient,
  $
    c_k
    =
    -
    sum_(i=k+1)^n
    mu_(i,k) z_i.
  $
  After $z_(k+1), dots, z_n$ have been fixed, $c_k$ is the real-valued coefficient that would make the current GSO residual equal to zero. It is a local continuous center, not the global SVP solution and not a policy decision.

- $y_k$: residual GSO coordinate,
  $
    y_k
    =
    z_k - c_k
    =
    z_k
    +
    sum_(i=k+1)^n
    mu_(i,k) z_i.
  $
  It measures how far the chosen integer $z_k$ lies from the local continuous center.

- $rho_(k+1)$: accumulated irreversible GSO squared-norm contribution from the already fixed levels,
  $
    rho_(k+1)
    =
    sum_(j=k+1)^n
    g_j y_j^2.
  $
  This is not the Euclidean norm of the raw partial vector. It is a lower bound on the final squared norm because future lower-index coefficients cannot remove these already fixed orthogonal contributions.

- $Delta_k$: maximum allowed residual distance from $c_k$ under the current global radius,
  $
    Delta_k
    =
    sqrt((R^2 - rho_(k+1)) / g_k).
  $

- $R$: current global search radius, equal to the norm of the best complete nonzero vector found so far. It is shared by the whole search tree.

- $R_0$: reference radius at the beginning and remains fixed of one search episode (the period when Basis fixed).

- $R_b$: best complete vector length obtained by the end of the episode.

== Search State and Network

- $s$: one MCTS state, corresponding to one partial coefficient assignment under the current basis.
- $a$: one action. In this project,
  $
    a = z_k.
  $
- $A(s)$: the mathematically legal integer actions at state $s$.
- $u_theta(s, a)$: policy logit assigned by the network to candidate action $a$.
- $P_theta(s, a)$: policy prior obtained by normalizing the logits over legal candidate actions.
- $V_theta(s)$: value-head prediction for state $s$.
- $J$: exact terminal score associated with a complete vector.
- $Y$: value backed up by one MCTS simulation. It is exact at terminal leaves and predicted at non-terminal leaves.
- $S(s,a)$: MCTS branch-selection score.
- $pi(s, a)$: MCTS-improved policy target derived from visit counts.
- $tau$: temperature used when converting visit counts into $pi$.

== MCTS Edge Statistics

- $P(s,a)$: stored policy prior for edge $(s,a)$.
- $N(s,a)$: number of MCTS simulations that selected branch $(s,a)$ (used to save calculation time and resources).
- $N_p$: total visit count of current node .
- $W(s,a)$: accumulated backed-up value on edge $(s,a)$.
- $Q(s,a)$: empirical mean backed-up value,
  $
    Q(s,a) = W(s,a) / N(s,a).
  $
- $M(s,a)$: best exact terminal score ever found through edge $(s,a)$.
- $U(s,a)$: PUCT exploration term.

== Search Hyperparameters

- $lambda_"PUCT"$: exploration coefficient in the PUCT rule.
- $K(s)$: number of actions currently expanded at state $s$.
- $C_"PW"$: progressive-widening scale parameter.
- $d_"PW"$: progressive-widening exponent, with
  $
    0 < d_"PW" < 1.
  $
- $w_M$: weight assigned to the maximum-value statistic $M$ in the SVP-specific selection rule.

== Abbreviations

- *SV*: Shortest Vector.
- *SVP*: Shortest Vector Problem.
- *MCTS*: Monte Carlo Tree Search.
- *UCB*: Upper Confidence Bound.
- *UCT*: Upper Confidence bounds applied to Trees.
- *PUCT*: policy-prior-guided UCT-style selection used inside MCTS.

= 1. Goal

Let $B$ be a basis of a fixed target lattice $L(B)$. A good complete nonzero lattice vector is already exist ($b_1$) with norm $R_0$ ($norm/(G H) approx 0.99$).

Every lattice vector considered by the enumeration has the form

$
  v
  =
  B z
  =
  sum_(i=1)^n z_i b_i,
  quad
  z_i in ZZ.
$

Aimed at finding a vector with norm smaller than the current best radius $R$ as efficiently as possible.

The architecture separates three responsibilities:

- *Exact enumeration geometry* decides which coefficient choices are mathematically possible under the current radius.
- *The policy-value network* estimates which legal branches are promising.
- *MCTS* allocates the finite search budget among those legal branches.


= 2. Coefficient Search Tree

== 2.1 Why the tree searches coefficients

The unknown object is the integer vector

$
  z
  =
  (z_1, dots, z_n).
$

Instead of predicting all coefficients at once, the search chooses them sequentially:

$
  z_n
  ->
  z_(n-1)
  ->
  dots
  ->
  z_1.
$

Each node represents a partial coefficient assignment.

At level $k$, the coefficients

$
  z_(k), dots, z_n
$

have already been fixed, while

$
  z_(k-1), dots, z_1
$

are still unknown.

The next action is

$
  a = z_(k-1).
$

A complete root-to-leaf path determines the full integer vector $z$ and therefore the complete lattice vector

$
  v = B z.
$


== 2.2 Why enumeration runs backward

GSO is important and constructed forward:

$
  b_1^*
  ->
  b_2^*
  ->
  dots
  ->
  b_n^*.
$

This is necessary because $b_i^*$ is computed using the earlier orthogonal vectors.

However, enumeration runs backward. There is no contradiction.

From the GSO decomposition,

$
  b_i
  =
  b_i^*
  +
  sum_(j=1)^(i-1)
  mu_(i,j) b_j^*,
$

we substitute into

$
  v & = sum_(i=1)^n z_i b_i, \
    & = sum_(k=1)^n y_k b_k^*
$
where

$
  y_k
  =
  z_k
  +
  sum_(i=k+1)^n
  mu_(i,k) z_i.
$

Therefore $y_k$ depends on

$
  z_k, z_(k+1), dots, z_n.
$

To evaluate the $k$-th orthogonal coordinate exactly, the higher-index coefficients must already be known. Hence the natural order is

$
  z_n
  ->
  z_(n-1)
  ->
  dots
  ->
  z_1.
$

This is analogous to first constructing a triangular factorization and then solving it by backward substitution.

== 2.3 What $z$, $c$, and $y$ mean

The three quantities have different roles:

- $z_k$: the actual integer decision.
- $c_k$: the local real-valued center implied by already fixed higher-index coefficients.
- $y_k$: the residual after the integer decision is compared with that center.

Define

$
  c_k
  =
  -
  sum_(i=k+1)^n
  mu_(i,k) z_i.
$

Then

$
  y_k = z_k - c_k.
$

If $z_k$ were allowed to be any real number, choosing

$
  z_k = c_k
$

would make the current orthogonal residual $y_k$ equal to zero.

However, $z_k$ must be an integer. Therefore $c_k$ is only a local continuous center around which legal integers are considered. $c_k "and" Delta thin$ form a boundary for $z_i$ enumeration.


= 3. Exact GSO Bound and Finite Actions

== 3.1 Norm decomposition and irreversible bound

The GSO representation of a full lattice vector is
$
  v = sum_(k=1)^n y_k b_k^*,
$
where
$
  y_k = z_k - c_k, quad
  c_k = - sum_(i=k+1)^n mu_(i,k) z_i .
$
Because the $b_i^*$ are mutually orthogonal,
$
  norm(v)^2 = sum_(k=1)^n g_k y_k^2, quad g_k = norm(b_k^*)^2 .
$
Every term $g_k y_k^2 >= 0$, so the sum gives a non‑negative decomposition.

After $z_(k+1), dots, z_n$ have been fixed, the already locked‑in contribution is
$
  rho_(k+1) = sum_(j=k+1)^n g_j y_j^2 .
$
For any completion,
$
  norm(v)^2 = rho_(k+1) + g_k y_k^2 + sum_(j=1)^(k-1) g_j y_j^2 >= rho_(k+1) .
$
Thus $rho_(k+1)$ is an irreversible lower bound: lower‑index coefficients can never cancel it.
If $rho_(k+1) >= R^2$, the branch cannot yield a vector shorter than the current radius $R$ and is pruned exactly.

== 3.2 Legal coefficient interval

A branch remains viable only while the next choice can still satisfy
$
  rho_(k+1) + g_k (z_k - c_k)^2 < R^2 .
$
This condition is equivalent to
$
  |z_k - c_k| < sqrt((R^2 - rho_(k+1)) / g_k) =: Delta_k .
$
Therefore the legal action set at depth $k$ is the finite integer interval
$
  A(s) = { z_k in ZZ : |z_k - c_k| < Delta_k } .
$

The quantities have the following roles:
- $R^2 - rho_(k+1)$: remaining length budget,
- $g_k$: cost of a unit displacement along $b_k^*$,
- $Delta_k$: maximum allowed distance from the local center $c_k$,
- $c_k$: center of the legal integer interval.

A smaller global radius $R$ shrinks every $Delta_k$ and thus strengthens pruning throughout the tree.

= 4. Network Design and Training

== 4.1 Search state and input features

=== 4.1.1 Mathematical state

One MCTS node corresponds to a partial coefficient assignment $s$.
The exact backend maintains:
- current depth $k$,
- fixed coefficients $z_(k+1), dots, z_n$,
- accumulated bound $rho_(k+1)$,
- global radius $R$,
- GSO data ($mu_(i,j)$, $g_i$) needed for $c_k$ and $Delta_k$.

$ast R$ is shared by the whole tree.

=== 4.1.2 Network inputs

The network receives normalized geometric features, not raw coordinates:
$
  k/n, quad
  rho_(k+1) / R^2, quad
  R / (G H),
$
together with (log‑)normalized $g_i$, recent residuals $y_i$, and for each candidate action:
$
  (a - c_k) / Delta_k .
$

The representation is a modelling choice; the network never replaces exact bounds.

=== 4.1.3 Lattice specialist

A single parameter set $theta_L$ serves one target lattice $L$.
All nodes in the tree call the same network.
The aim is instance specialization: repeated searches on the same lattice learn its coefficient‑search landscape.
The specialist adapts to unimodular basis changes (e.g., LLL) that preserve the lattice.

== 4.2 Policy head

=== 4.2.1 Architecture

The policy head scores every legal candidate $a in A(s)$ with a logit $u_theta(s, a)$.
The prior is obtained by softmax over the legal set:
$
  P_theta(s, a) = e^(u_theta(s, a)) / sum_(b in A(s)) e^(u_theta(s, b)) .
$
$A(s)$ is dynamic, so the head must evaluate an arbitrary finite set of integers.
A low prior never overrides exact legality; pruning is only done by the GSO bound.

=== 4.2.2 Learning the prior

After MCTS, an improved policy is built from visit counts with temperature $tau$:
$
  pi(s, a) = N(s, a)^(1/tau) / sum_b N(s, b)^(1/tau) .
$
The policy head is trained by cross‑entropy:
$
  cal(L)_"policy" = - sum_a pi(s, a) log P_theta(s, a) .
$
The loop is: network prior → MCTS → visit‑count policy → updated network.
Within one search episode the stored prior $P(s,a)$ is frozen; backups update search statistics, not network parameters.

== 4.3 Value head and reward

=== 4.3.1 Value head

The value head outputs $V_theta(s)$, a learned estimate of subtree promise under a fixed search budget.
It is a heuristic, not a mathematical bound, and must never be used for exact pruning.

=== 4.3.2 Terminal score

The reference radius $R_0$ is fixed per episode.
For a complete vector $v$ (with $v != 0$), the exact score is
$
  J(v) = n log(R_0 / norm(v)) .
$
$J(v) = 0$ when $norm(v) = R_0$, and $J(v) > 0$ for any improvement.
The logarithm turns multiplicative improvements into additive rewards, and the factor $n$ keeps small relative gains numerically visible in high dimensions.

=== 4.3.3 Value target

A practical target for $V_theta$ is the best terminal score eventually found from state $s$ under a given node budget.
Expected return is an alternative.
For SVP, the exact definition of the value target remains an experimental choice.
== 7.1 Selection

For an already expanded action, the standard policy-guided score is

$
  S(s,a)
  =
  Q(s,a)
  +
  U(s,a),
$

with

$
  U(s,a)
  =
  lambda_"PUCT"
  P(s,a)
  sqrt(N_p)
  /
  (1 + N(s,a)).
$

Interpretation:

- $Q$: empirical quality already observed;
- $P$: learned prior preference;
- $N(s,a)$: how much effort the edge has already received;
- $N_p$: how mature the parent node is;
- $U$: exploration pressure.

A low-visit branch is not necessarily bad. Because $N(s,a)$ appears in the denominator, an insufficiently tested branch may regain exploration priority.

If it is tested repeatedly and remains poor, then $N$ rises, $U$ falls, and low $Q$ causes it to lose priority naturally.

This is very different from exact pruning:

- pruning means "this branch cannot improve $R$";
- low PUCT priority means "this branch is not worth much budget now."

== 7.2 Why UCB appears behind PUCT

The exploration idea comes from UCB.

For bounded rewards, Hoeffding-type concentration gives

$
  "Pr"(
    mu - Q_N >= epsilon
  )
  <=
  e^(-2 N epsilon^2).
$

Choosing a failure probability that decreases polynomially with time and solving for $epsilon$ yields a radius proportional to

$
  sqrt(log(t) / N).
$

This motivates

$
  "estimate"
  +
  "confidence bonus".
$

UCT applies the same exploration-exploitation idea recursively in trees.

PUCT is a policy-prior-guided variant. Its formula is not itself the original Hoeffding confidence interval, so $lambda_"PUCT"$ is a tunable hyperparameter rather than a universal theorem-derived constant.

= 8. Expansion and Progressive Widening

The GSO interval makes $A(s)$ finite, but it can still contain many integers.

Creating every child immediately may waste memory and search effort.

Let $K(s)$ be the number of currently expanded actions. Progressive widening allows roughly

$
  K(s)
  <=
  C_"PW" N(s)^d_"PW",
  quad
  0 < d_"PW" < 1.
$

Thus important nodes gradually expose more actions, while branching grows sublinearly with visits.

Progressive widening answers *when* another action may be opened. It does not decide *which* integer to open.

Possible proposal orders include:

- Schnorr-Euchner order around $c_k$;
- learned policy order;
- a mixture of the two with explicit global exploration.

If exact completeness is eventually required, every mathematically legal action must remain reachable.

= 9. Evaluation and Backup

== 9.1 Terminal evaluation

When all coefficients are fixed,

$
  z = (z_1, dots, z_n),
$

construct

$
  v = B z.
$

If $v != 0$ and

$
  norm(v) < R,
$

update the shared incumbent:

$
  R <- norm(v).
$

This immediately tightens future GSO bounds.

The complete vector norm may be checked directly from $B z$. GSO is essential for partial lower bounds, not because direct full-vector evaluation is impossible.

== 9.2 Non-terminal evaluation

If the selected leaf is incomplete, evaluate it with

$
  V_theta(s_"leaf").
$

This avoids forcing every simulation to enumerate all the way to a complete vector.

== 9.3 Unified backup

Define the simulation value

$
  Y
  =
  cases(
    J(v) & "terminal leaf",
    V_theta(s_"leaf") & "non-terminal evaluated leaf".
  )
$

Then along the selected path,

$
  N <- N + 1,
$

$
  W <- W + Y,
$

$
  Q <- W / N.
$

For exact terminal evidence only,

$
  M <- max(M, J(v)).
$

Therefore:

- $P$: learned prior;
- $N$: search effort;
- $W$: accumulated returned value;
- $Q$: mean returned value;
- $M$: best exact terminal value found through the edge.

$M$ should not be updated with an optimistic neural prediction.

= 10. Why Add the Extreme-Value Term M?

Standard MCTS is mainly mean-value oriented through $Q$.

SVP is different: one exceptional leaf can matter more than many ordinary leaves.

Suppose branch A is consistently moderate, while branch B is usually weak but has once produced a much shorter vector. Then branch B may have lower $Q$ but much higher $M$.

A candidate SVP-specific score is

$
  S(s,a)
  =
  (1 - w_M) Q(s,a)
  +
  w_M M(s,a)
  +
  U(s,a).
$

For example,

$
  w_M = 0.25
$

gives

$
  S
  =
  0.75 Q
  +
  0.25 M
  +
  U.
$

This is only an experimental starting point.

The baseline must include

$
  w_M = 0,
$

which recovers mean-value PUCT.

The purpose of $M$ is to preserve demonstrated extreme potential without allowing one lucky outcome to dominate the search completely.

= 11. Complete Search Procedure

Under one fixed basis:

1. Start from a good complete incumbent with radius $R_0$.
2. Set the shared global radius $R = R_0$.
3. Compute GSO data for the basis.
4. Create one MCTS root.
5. At each node, derive $c_k$, $rho_(k+1)$, $Delta_k$, and the legal integer set.
6. Prune exactly when $rho_(k+1) >= R^2$.
7. Use the policy head to assign priors to legal actions.
8. Use PUCT to select among expanded children.
9. Use progressive widening when another action may be opened.
10. Evaluate terminal leaves exactly and non-terminal leaves with $V_theta$.
11. Backup $N$, $W$, and $Q$; update $M$ only from exact terminal scores.
12. If a complete vector improves the incumbent, reduce the global $R$.
13. Continue under the tighter bounds until the search budget is exhausted.

The main feedback loop is

$
  "better vector"
  ->
  "smaller R"
  ->
  "smaller coefficient intervals"
  ->
  "more pruning"
  ->
  "more concentrated search".
$

= 12. Lattice-Specialized Training

For one fixed target lattice $L$, maintain one specialist network

$
  theta_L.
$

Repeated searches generate state-policy-value data from that same lattice.

The specialist is trained to improve:

- policy ordering through $pi$;
- subtree evaluation through the selected value target.

This design deliberately favors deep instance specialization over universal cross-lattice generalization.

The comparison must include training cost. If specialization consumes substantial compute, that cost belongs to the total budget.

Useful metrics are:

- best norm after fixed wall-clock time;
- best norm after fixed node count;
- time or nodes to first improvement;
- neural inference overhead;
- cumulative training plus search cost.

= 13. Traditional Enumeration, Basis Changes, and Limits

== 13.1 Difference from traditional enumeration

Traditional Schnorr-Euchner-style enumeration and this method may share:

- GSO;
- exact radius bounds;
- dynamic incumbent updates;
- exact pruning.

The main difference is search priority.

Traditional enumeration mainly uses hand-designed ordering and pruning heuristics.

MCTS-in-Enumeration adds learned, state-dependent search priorities and adaptive allocation of simulation budget.

The research claim is therefore not that classical enumeration is naive. The question is whether learned prioritization improves *anytime performance* under equal cumulative compute.

== 13.2 Optional LLL outer loop

A unimodular basis change

$
  B_"new" = B U
$

preserves the lattice but changes the search coordinates.

After a substantial LLL or basis update:

- $mu$, $g$, $c$, $y$, and coefficient coordinates change;
- the old MCTS tree should normally be rebuilt;
- the lattice-specialist network may be retained and adapted.

A useful design principle is:

#quote[
  The tree belongs to the current basis; the specialist network belongs to the target lattice.
]

A later outer loop may be

$
  "MCTS"
  ->
  "better vector"
  ->
  "basis update + LLL"
  ->
  "new GSO"
  ->
  "restart MCTS".
$

This should be evaluated separately from the fixed-basis method so that gains from learning are not confused with gains from basis reduction.

== 13.3 Important limits

- A best-known vector is not automatically the exact shortest vector.
- $norm(v) / G H = 0.98$ does not mean "within 2 percent of the optimum."
- MCTS is not automatically more memory-efficient than DFS enumeration.
- Neural inference and training cost may exceed the cost saved by fewer node expansions.
- Neural predictions may reorder legal branches, but exact pruning should remain mathematical if completeness is required.

= 14. Currently Unsolved

The following quantities or design choices are not learned automatically and must be determined experimentally.

== 14.1 Extreme-Value Objective

Selection may use

$
  S(s,a)
  =
  (1 - w_M) Q(s,a)
  +
  w_M M(s,a)
  +
  U(s,a).
$

The choice of objective and the weight $w_M$ remain experimental.

== 14.2 Value Target and Search Budget

The meaning of $V_theta(s)$ must be fixed explicitly, for example expected terminal quality or best result under a search budget $B$.

Both the target definition and $B$ are experimental choices.

== 14.3 Policy Temperature

The visit-count target is

$
  pi(s, a)
  =
  N(s,a)^(1 / tau)
  /
  sum_b N(s,b)^(1 / tau).
$

The temperature $tau$ controls how concentrated the target policy is and must be tuned.

== 14.4 PUCT Exploration

$
  U(s,a)
  =
  lambda_"PUCT"
  P(s,a)
  sqrt(N_p)
  /
  (1 + N(s,a)).
$

The exploration coefficient $lambda_"PUCT"$ must be calibrated to the scale of $Q$ and $M$.

== 14.5 Progressive Widening

$
  K(s)
  <=
  C_"PW" N(s)^d_"PW",
  quad
  0 < d_"PW" < 1.
$

Both $C_"PW"$ and $d_"PW"$ are empirical hyperparameters.

== 14.6 Action Proposal

When progressive widening opens a new action, the proposal may follow Schnorr-Euchner order, learned policy order, or a mixture.

Any mixture or exploration ratio must be chosen experimentally.

== 14.7 State and Network Design

The state representation, local GSO window, network width and depth, and inference frequency are design choices rather than learned quantities.

== 14.8 Training Hyperparameters

If gradient training is used, quantities such as learning rate, batch size, value-loss weight, regularization strength, and update frequency must be tuned experimentally.

== 14.9 Radius Tightening and Tree Reuse

After $R$ decreases, it remains open whether stale nodes and their $N$, $W$, $Q$, and $M$ should be retained, revalidated, or reset.

== 14.10 Basis Transfer

After LLL changes the basis, the lattice is unchanged but the coordinates are different. Network transfer and replay-data reuse remain experimental design choices.

== 14.11 Specialist versus Generalist

The benefit of one-lattice specialization versus cross-lattice training must be evaluated under equal cumulative compute.

== 14.12 Computational Cost

The network architecture and inference frequency should be chosen so that saved enumeration work exceeds neural training and inference cost.

== 14.13 Theory

Classical UCB/UCT theory does not directly establish convergence or optimality for the combined PUCT, progressive-widening, learned-prior, and extreme-value design.

#quote[
  GSO and radius bounds determine what is possible. MCTS and learning determine what is worth trying first.
]
